# see https://docs.silverstripe.org/en/developer_guides/configuration/configuration/
dannidickson\prismatic\Configuration:
  allowed_classes:
    - Page
    - BaseElement


# see https://docs.silverstripe.org/en/developer_guides/configuration/configuration/
---
Name: prismatic
After:
  - "#silverstripe-react"
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - "dannidickson/prismatic: client/dist/js/bundle.js"
  extra_requirements_css:
    - "dannidickson/prismatic: client/dist/styles/bundle.css"
